### PR TITLE
update on backend request, prettierc format, validations

### PR DESCRIPTION
**Pull request by irarayzelji2002**
Bug: results not working for ip address inputted
What's done: 
- added separate request url if has ipInput

Enhancement: 
- added prettierc to have same format and avoid spaces detected as changes (run npm i)
- added more validations on ipv4 and ipv6

For Testing:
- test all kinds of IPv4 and IPv6 address, check it's showing the correct fields from the response.test in teminal logs
- test no input, should return current ip data as results

### CODE REVIEW

**Comment by aliahestbn** [comment]
Thanks for the update! I’ve already tested the changes, and everything looks good. The additional validations and formatting are a great improvement.

**Review by aliahestbn — COMMENTED** [review]
Thanks for the update.

**Review by aliahestbn — COMMENTED** [review]
Thanks for the update, Ira! I’ve already tested the changes, and everything looks good. The additional validations and formatting are a great improvement.

**Review by JakobPalomo — COMMENTED** [review]
Looks good to me

**Pull request merged**
