### PR TITLE
updated the ReadMe instructions

### PR DESCRIPTION
**Pull request by JakobPalomo**
Hello team, I added some more instructions to setting up the environment part of README.md, does it look good?

### CODE REVIEW

**Comment by irarayzelji2002** [comment]
sure, this looks good!

**Comment by YnaSophiaDR** [comment]
It looks good to me! Thank you so much.

**Review by irarayzelji2002 — APPROVED** [review]

**Review by aliahestbn — COMMENTED** [review]
Done reviewing, it looks good. Thank you and have a great day!

**Review by YnaSophiaDR — COMMENTED** [review]
Approved!

**Comment by JakobPalomo** [comment]
Thank you everyone!

**Pull request merged**
